In [108]:
import numpy as np 
import pandas as pd

In [110]:
df=pd.read_csv('Loan_approval_data_2025.csv')
df.head()

,customer_id,age,occupation_status,years_employed,annual_income,credit_score,credit_history_years,savings_assets,current_debt,defaults_on_file,delinquencies_last_2yrs,derogatory_marks,product_type,loan_intent,loan_amount,interest_rate,debt_to_income_ratio,loan_to_income_ratio,payment_to_income_ratio,loan_status
0,CUST100000,40,Employed,17.2,25579,692,5.3,895,10820,0,0,0,Credit Card,Business,600,17.02,0.423,0.023,0.008,1
1,CUST100001,33,Employed,7.3,43087,627,3.5,169,16550,0,1,0,Personal Loan,Home Improvement,53300,14.10,0.384,1.237,0.412,0
2,CUST100002,42,Student,1.1,20840,689,8.4,17,7852,0,0,0,Credit Card,Debt Consolidation,2100,18.33,0.377,0.101,0.034,1
3,CUST100003,53,Student,0.5,29147,692,9.8,1480,11603,0,1,0,Credit Card,Business,2900,18.74,0.398,0.099,0.033,1
4,CUST100004,32,Employed,12.5,63657,630,7.2,209,12424,0,0,0,Personal Loan,Education,99600,13.92,0.195,1.565,0.522,1

In [112]:
# initial exploration

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              50000 non-null  object
 1   age                      50000 non-null  int64
 2   occupation_status        50000 non-null  object
 3   years_employed           50000 non-null  float64
 4   annual_income            50000 non-null  int64
 5   credit_score             50000 non-null  int64
 6   credit_history_years     50000 non-null  float64
 7   savings_assets           50000 non-null  int64
 8   current_debt             50000 non-null  int64
 9   defaults_on_file         50000 non-null  int64
 10  delinquencies_last_2yrs  50000 non-null  int64
 11  derogatory_marks         50000 non-null  int64
 12  product_type             50000 non-null  object
 13  loan_intent              50000 non-null  object
 14  loan_amount              50000 non-null  int64
 15  interest_rate            50000 non-null  float64
 16  debt_to_income_ratio     50000 non-null  float64
 17  loan_to_income_ratio     50000 non-null  float64
 18  payment_to_income_ratio  50000 non-null  float64
 19  loan_status              50000 non-null  int64
dtypes: float64(6), int64(10), object(4)
memory usage: 7.6+ MB

In [114]:
# checking for null values

df.isnull().sum()

customer_id                0
age                        0
occupation_status          0
years_employed             0
annual_income              0
credit_score               0
credit_history_years       0
savings_assets             0
current_debt               0
defaults_on_file           0
delinquencies_last_2yrs    0
derogatory_marks           0
product_type               0
loan_intent                0
loan_amount                0
interest_rate              0
debt_to_income_ratio       0
loan_to_income_ratio       0
payment_to_income_ratio    0
loan_status                0
dtype: int64

In [116]:
df.head()

,customer_id,age,occupation_status,years_employed,annual_income,credit_score,credit_history_years,savings_assets,current_debt,defaults_on_file,delinquencies_last_2yrs,derogatory_marks,product_type,loan_intent,loan_amount,interest_rate,debt_to_income_ratio,loan_to_income_ratio,payment_to_income_ratio,loan_status
0,CUST100000,40,Employed,17.2,25579,692,5.3,895,10820,0,0,0,Credit Card,Business,600,17.02,0.423,0.023,0.008,1
1,CUST100001,33,Employed,7.3,43087,627,3.5,169,16550,0,1,0,Personal Loan,Home Improvement,53300,14.10,0.384,1.237,0.412,0
2,CUST100002,42,Student,1.1,20840,689,8.4,17,7852,0,0,0,Credit Card,Debt Consolidation,2100,18.33,0.377,0.101,0.034,1
3,CUST100003,53,Student,0.5,29147,692,9.8,1480,11603,0,1,0,Credit Card,Business,2900,18.74,0.398,0.099,0.033,1
4,CUST100004,32,Employed,12.5,63657,630,7.2,209,12424,0,0,0,Personal Loan,Education,99600,13.92,0.195,1.565,0.522,1

In [118]:
# Creating some New columns 1. age group

df['age_group']=pd.qcut(df['age'],q=4,labels=['Young','Young Adults','Middle-aged','Older adults'])

In [120]:
df[['age','age_group']].head()

   age     age_group
0   40   Middle-aged
1   33  Young Adults
2   42   Middle-aged
3   53  Older adults
4   32  Young Adults

In [122]:
# 2.Credit score segmentation
l=[]
for i in df['credit_score']:
    if i <580:
        l.append('Low')
    elif i>=580 and i<670:
        l.append('Fair')
    elif i>=670 and i<740:
        l.append('Good')
    elif i>=740 :
        l.append('Excellent')

df['credit_tier']=l

df[['credit_score','credit_tier']].head()

   credit_score credit_tier
0           692        Good
1           627        Fair
2           689        Good
3           692        Good
4           630        Fair

In [124]:
df=df[['customer_id', 'age', 'age_group','occupation_status', 'years_employed',
       'annual_income', 'credit_score', 'credit_history_years', 'credit_tier',
       'savings_assets', 'current_debt', 'defaults_on_file',
       'delinquencies_last_2yrs', 'derogatory_marks', 'product_type',
       'loan_intent', 'loan_amount', 'interest_rate', 'debt_to_income_ratio',
       'loan_to_income_ratio', 'payment_to_income_ratio', 'loan_status']]

df.head()

,customer_id,age,age_group,occupation_status,years_employed,annual_income,credit_score,credit_history_years,credit_tier,savings_assets,...,delinquencies_last_2yrs,derogatory_marks,product_type,loan_intent,loan_amount,interest_rate,debt_to_income_ratio,loan_to_income_ratio,payment_to_income_ratio,loan_status
0,CUST100000,40,Middle-aged,Employed,17.2,25579,692,5.3,Good,895,...,0,0,Credit Card,Business,600,17.02,0.423,0.023,0.008,1
1,CUST100001,33,Young Adults,Employed,7.3,43087,627,3.5,Fair,169,...,1,0,Personal Loan,Home Improvement,53300,14.10,0.384,1.237,0.412,0
2,CUST100002,42,Middle-aged,Student,1.1,20840,689,8.4,Good,17,...,0,0,Credit Card,Debt Consolidation,2100,18.33,0.377,0.101,0.034,1
3,CUST100003,53,Older adults,Student,0.5,29147,692,9.8,Good,1480,...,1,0,Credit Card,Business,2900,18.74,0.398,0.099,0.033,1
4,CUST100004,32,Young Adults,Employed,12.5,63657,630,7.2,Fair,209,...,0,0,Personal Loan,Education,99600,13.92,0.195,1.565,0.522,1

In [128]:
# checking for any duplicated rows

df.duplicated().sum()

0

In [141]:
# 3. income bucket column

df['income_bucket']=pd.qcut(df['annual_income'],q=3,labels=['Low income','Middle income','High income'])

df[['annual_income','income_bucket']]

       annual_income  income_bucket
0              25579     Low income
1              43087  Middle income
2              20840     Low income
3              29147     Low income
4              63657    High income
...              ...            ...
49995          39449  Middle income
49996          20496     Low income
49997          18743     Low income
49998          17250     Low income
49999          46923  Middle income

[50000 rows x 2 columns]

# Connecting to MySql for deeper analysis

In [143]:
from sqlalchemy import create_engine

# MySQL connection
username = "root"
password = "admin"
host = "localhost"
port = "3306"
database = "Project"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Write DataFrame to MySQL
table_name = "loan_approval"   
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM loan_approval LIMIT 5;", engine)

,customer_id,age,age_group,occupation_status,years_employed,annual_income,credit_score,credit_history_years,credit_tier,savings_assets,...,derogatory_marks,product_type,loan_intent,loan_amount,interest_rate,debt_to_income_ratio,loan_to_income_ratio,payment_to_income_ratio,loan_status,income_bucket
0,CUST100000,40,Middle-aged,Employed,17.2,25579,692,5.3,Good,895,...,0,Credit Card,Business,600,17.02,0.423,0.023,0.008,1,Low income
1,CUST100001,33,Young Adults,Employed,7.3,43087,627,3.5,Fair,169,...,0,Personal Loan,Home Improvement,53300,14.10,0.384,1.237,0.412,0,Middle income
2,CUST100002,42,Middle-aged,Student,1.1,20840,689,8.4,Good,17,...,0,Credit Card,Debt Consolidation,2100,18.33,0.377,0.101,0.034,1,Low income
3,CUST100003,53,Older adults,Student,0.5,29147,692,9.8,Good,1480,...,0,Credit Card,Business,2900,18.74,0.398,0.099,0.033,1,Low income
4,CUST100004,32,Young Adults,Employed,12.5,63657,630,7.2,Fair,209,...,0,Personal Loan,Education,99600,13.92,0.195,1.565,0.522,1,High income

In [ ]:
# # income bucket ,age group, credit score segmentation, loan amount bucket

# customer id 
# age 
# occupation status
# years employed
# annual income
# credit score
# credit history years
# saving assets
# current debt
# defaults on file
# deliquencies last 2 years 
# derogatory marks
# product type 
# loan intent
# loan amt
# interest rate 
# debt to income ratio 
# laon to income ratio
# payment to income ratio
# loan_status